// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcialAncelmo.Database;

namespace ParcialAncelmo.Migrations
{
    [DbContext(typeof(Conexao))]
    [Migration("20210415152345_novo")]
    partial class novo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParcialAncelmo.Models.Autor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("linkedin")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("nome")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            linkedin = "www.linkedin.com/in/josefina-silva/",
                            nome = "Josefina da Silva"
                        });
                });

            modelBuilder.Entity("ParcialAncelmo.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("endereco")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("nome")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("sexo")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("telefone")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            dataDeNascimento = new DateTime(2021, 4, 15, 11, 23, 45, 203, DateTimeKind.Local).AddTicks(4442),
                            email = "teste123@gmail.com",
                            endereco = "Avenida Rafael Vaz e Silva, 1111, Liberdade, Porto Velho, Rondônia",
                            nome = "Juscelino Peres",
                            sexo = "Masculino",
                            telefone = "69 9999999999"
                        });
                });

            modelBuilder.Entity("ParcialAncelmo.Models.Conteudo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataDeCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idAutor")
                        .HasColumnType("int");

                    b.Property<int>("idTipoConteudo")
                        .HasColumnType("int");

                    b.Property<string>("link")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("texto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(10000);

                    b.HasKey("id");

                    b.HasIndex("idAutor");

                    b.HasIndex("idTipoConteudo");

                    b.ToTable("Conteudos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            dataDeCadastro = new DateTime(2021, 4, 15, 11, 23, 45, 205, DateTimeKind.Local).AddTicks(5568),
                            idAutor = 0,
                            idTipoConteudo = 0,
                            link = "siojaoisjaoijsiojoia",
                            texto = "sokaoskoaksok"
                        });
                });

            modelBuilder.Entity("ParcialAncelmo.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<double>("valor")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("idCliente");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descricao = "nsiasiuhauhs",
                            idCliente = 0,
                            valor = 100.0
                        });
                });

            modelBuilder.Entity("ParcialAncelmo.Models.TipoConteudo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.HasKey("id");

                    b.ToTable("TipoConteudos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descricao = "isjaoijsoiaj"
                        });
                });

            modelBuilder.Entity("ParcialAncelmo.Models.Conteudo", b =>
                {
                    b.HasOne("ParcialAncelmo.Models.Autor", "autor")
                        .WithMany()
                        .HasForeignKey("idAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParcialAncelmo.Models.TipoConteudo", "tipoConteudo")
                        .WithMany()
                        .HasForeignKey("idTipoConteudo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParcialAncelmo.Models.Produto", b =>
                {
                    b.HasOne("ParcialAncelmo.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
